# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Winchester Cycling Charter
email: contact@winchestercyclingcharter.org.uk
description: >- # this means to ignore newlines until "baseurl:"
  We want our historic city and surrounding countryside to be a vibrant, 
  sustainable and healthy place in which to live, work, do business, study 
  and thrive.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://winchestercyclingcharter.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter:
  username: winchestercyclingcharter
  card: summary
github_username:  winchestercyclingcharter
github: [metadata]
phase: prelaunch # suppress features not wanted until launch
exclude: [ind-page.md, org-page.md, supporters.md, thanks.md]
kramdown:
  auto_ids: true

google_analytics: G-N79TL41XX5

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-seo-tag
sass:
  sass_dir: assets/css
  style: compressed

collections:
  - orgs
  - people
